# Generated by Django 4.1.2 on 2022-12-12 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(max_length=255)),
                ("pin", models.IntegerField(unique=True)),
                ("password", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
